ERRORMSG_SEARCH_REQUIRED = 'Search query is required.'
USERNAME_CONTAINS = 'Username can only contain letters, numbers and underscores.'
USER_ALREADY_TAKEN = 'Username already taken.'
MOVIE_NOT_FOUND = 'Movie not found.'
USER_NOT_FOUND = 'User not found.'
PROGRESS_NOT_FOUND = 'Progress not found.'
