-- Curated movie selection for the new featured endpoint
INSERT INTO movies (imdbid, tmdbid, title, year, poster_url, backdrop_url, note, genre, summary) VALUES
    ('tt28650488', '1226863', 'The Super Mario Galaxy Movie', '2026',
    'https://image.tmdb.org/t/p/w500/eJGWx219ZcEMVQJhAgMiqo8tYY.jpg',
    'https://image.tmdb.org/t/p/w500/9Z2uDYXqJrlmePznQQJhL6d92Rq.jpg',
    8.164, ARRAY[10751, 35, 12, 14, 16],
    'Having thwarted Bowser''s previous plot to marry Princess Peach, Mario and Luigi now face a fresh threat in Bowser Jr., who is determined to liberate his father from captivity and restore the family legacy. Alongside companions new and old, the brothers travel across the stars to stop the young heir''s crusade.'),
    ('tt12042730', '687163', 'Project Hail Mary', '2026',
    'https://image.tmdb.org/t/p/w500/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
    'https://image.tmdb.org/t/p/w500/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg',
    8.67, ARRAY[878, 12],
    'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.'),
    ('tt1757678', '83533', 'Avatar: Fire and Ash', '2025',
    'https://image.tmdb.org/t/p/w500/bRBeSHfGHwkEpImlhxPmOcUsaeg.jpg',
    'https://image.tmdb.org/t/p/w500/u8DU5fkLoM5tTRukzPC31oGPxaQ.jpg',
    7.568, ARRAY[878, 12, 14],
    'In the wake of the devastating war against the RDA and the loss of their eldest son, Jake Sully and Neytiri face a new threat on Pandora: the Ash People, a violent and power-hungry Na''vi tribe led by the ruthless Varang. Jake''s family must fight for their survival and the future of Pandora in a conflict that pushes them to their emotional and physical limits.'),
    ('tt1650048', '110160', 'Laurence Anyways', '2012',
    'https://image.tmdb.org/t/p/w500/d8BpJ9qOQE7VFFqaV1XDdGfMsP7.jpg',
    'https://image.tmdb.org/t/p/w500/lNUP9ymEHolzjLIHyoAkpHRQZxq.jpg',
    7.626, ARRAY[18, 10749],
    'The story of an impossible love between a woman named Fred and a transgender woman named Laurence who reveals her inner desire to become her true self.'),
    ('tt26443616', '1327819', 'Hoppers', '2026',
    'https://image.tmdb.org/t/p/w500/xjtWQ2CL1mpmMNwuU5HeS4Iuwuu.jpg',
    'https://image.tmdb.org/t/p/w500/u53UYu5XG2hNgWGvs3xGhAVzypl.jpg',
    8.176, ARRAY[12, 16, 35, 10751, 878],
    'Scientists have discovered how to ''hop'' human consciousness into lifelike robotic animals, allowing people to communicate with animals as animals. Animal lover Mabel seizes an opportunity to use the technology, uncovering mysteries within the animal world beyond anything she could have imagined.'),
    ('tt33071426', '1325734', 'The Drama', '2026',
    'https://image.tmdb.org/t/p/w500/rnIOUhzwJDfgQakx8EjoNyItKgs.jpg',
    'https://image.tmdb.org/t/p/w500/rw1WmxUvmbwRsbAX12m6toIg04j.jpg',
    6.9, ARRAY[10749, 35, 18],
    'A happily engaged couple is put to the test when an unexpected turn sends their wedding week off the rails.'),
    ('tt0468569', '155', 'The Dark Knight', '2008',
    'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    'https://image.tmdb.org/t/p/w500/cfT29Im5VDvjE0RpyKOSdCKZal7.jpg',
    8.531, ARRAY[28, 80, 53],
    'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.'),
    ('tt0816692', '157336', 'Interstellar', '2014',
    'https://image.tmdb.org/t/p/w500/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
    'https://image.tmdb.org/t/p/w500/2ssWTSVklAEc98frZUQhgtGHx7s.jpg',
    8.478, ARRAY[12, 18, 878],
    'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.'),
    ('tt6751668', '496243', 'Parasite', '2019',
    'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    'https://image.tmdb.org/t/p/w500/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
    8.494, ARRAY[35, 53, 18],
    'All unemployed, Ki-taek''s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.'),
    ('tt5726616', '398818', 'Call Me by Your Name', '2017',
    'https://image.tmdb.org/t/p/w500/mZ4gBdfkhP9tvLH1DO4m4HYtiyi.jpg',
    'https://image.tmdb.org/t/p/w500/ssowCFz1rvHIe6jP0uGHIjQHz7T.jpg',
    8.1, ARRAY[10749, 18],
    'In the summer of 1983, a 17-year-old Elio spends his days in his family''s villa in Italy. One day Oliver, a graduate student, arrives to assist Elio''s father, a professor of Greco-Roman culture. Soon, Elio and Oliver discover a summer that will alter their lives forever.'),
    ('tt29623480', '1184918', 'The Wild Robot', '2024',
    'https://image.tmdb.org/t/p/w500/eG9lz41mJqsI4J6ubMtVqD26q2J.jpg',
    'https://image.tmdb.org/t/p/w500/1pmXyN3sKeYoUhu5VBZiDU4BX21.jpg',
    8.3, ARRAY[10751, 16, 878, 12],
    'After a shipwreck, an intelligent robot called Roz is stranded on an uninhabited island. To survive the harsh environment, Roz bonds with the island''s animals and cares for an orphaned baby goose.'),
    ('tt4633694', '324857', 'Spider-Man: Into the Spider-Verse', '2018',
    'https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
    'https://image.tmdb.org/t/p/w500/8mnXR9rey5uQ08rZAvzojKWbDQS.jpg',
    8.393, ARRAY[16, 28, 12, 878],
    'Struggling to find his place in the world while juggling school and family, Brooklyn teenager Miles Morales is unexpectedly bitten by a radioactive spider and develops unfathomable powers just like the one and only Spider-Man. While wrestling with the implications of his new abilities, Miles discovers a super collider created by the madman Wilson "Kingpin" Fisk, causing others from across the Spider-Verse to be inadvertently transported to his dimension.'),
    ('tt10370710', '313297', 'The Worst Person in the World', '2021',
    'https://image.tmdb.org/t/p/w500/1NxGNQchGBTHXJ6RShLY1IlZqWn.jpg',
    'https://image.tmdb.org/t/p/w500/woYGBHERSMhIHqmkkRCbCXp81l4.jpg',
    7.4, ARRAY[18, 10749, 35],
    'The chronicles of four years in the life of Julie, a young woman who navigates the troubled waters of her love life and struggles to find her career path, leading her to take a realistic look at who she really is.'),
    ('tt32916440', '660120', 'Marty Supreme', '2025',
    'https://image.tmdb.org/t/p/w500/lYWEXbQgRTR4ZQleSXAgRbxAjvq.jpg',
    'https://image.tmdb.org/t/p/w500/6h7w8R4BA7vubEmEEW5vYEjuoz6.jpg',
    7.388, ARRAY[18, 53],
    'Marty Mauser, a young man with a dream no one respects, goes to hell and back in pursuit of greatness.'),
    ('tt14905854', '858024', 'Hamnet', '2025',
    'https://image.tmdb.org/t/p/w500/vbeyOZm2bvBXcbgPD3v6o94epPX.jpg',
    'https://image.tmdb.org/t/p/w500/73BClq9FOcrWrutnpiqhCNEWEwJ.jpg',
    7.745, ARRAY[18, 10749, 36],
    'The powerful story of love and loss that inspired the creation of Shakespeare''s timeless masterpiece, Hamlet.'),
    ('tt0078788', '28', 'Apocalypse Now', '1979',
    'https://image.tmdb.org/t/p/w500/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg',
    'https://image.tmdb.org/t/p/w500/eN5G8vTWLnZxJ0LTd4g27oPObcZ.jpg',
    8.269, ARRAY[18, 10752],
    'At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission that, officially, "does not exist, nor will it ever exist." His goal is to locate - and eliminate - a mysterious Green Beret Colonel named Walter Kurtz, who has been leading his personal army on illegal guerrilla missions into enemy territory.'),
    ('tt8613070', '531428', 'Portrait of a Lady on Fire', '2019',
    'https://image.tmdb.org/t/p/w500/2LquGwEhbg3soxSCs9VNyh5VJd9.jpg',
    'https://image.tmdb.org/t/p/w500/ivJ5UzT6IzucLVfbZwCCwiJJoBz.jpg',
    8.1, ARRAY[18, 10749],
    'On an isolated island in Brittany at the end of the eighteenth century, a female painter is obliged to paint a wedding portrait of a young woman.'),
    ('tt10457128', '659959', 'Summer of 85', '2020',
    'https://image.tmdb.org/t/p/w500/etH2pm1eMxEjY2dlltpQGLVspv.jpg',
    'https://image.tmdb.org/t/p/w500/5NMxiETEUCT4297zrMdimNR5VqS.jpg',
    7.413, ARRAY[10749, 18],
    'What do you dream of when you''re 16-years-old and in a seaside resort in Normandy in the 1980s? A best friend? A lifelong teen pact? Scooting off on adventures on a boat or a motorbike? Living life at breakneck speed? No. You dream of death. Because you can''t get a bigger kick than dying. And that''s why you save it till the very end. The summer holidays are just beginning, and this story recounts how Alexis grew into himself.'),
    ('tt0079944', '1398', 'Stalker', '1979',
    'https://image.tmdb.org/t/p/w500/1qhOyf5C4s9ZdvY8d5JDx9DFMeT.jpg',
    'https://image.tmdb.org/t/p/w500/6yrbWzzrPp7pwz6zHdifspJk8t3.jpg',
    8.096, ARRAY[878, 18],
    'Near a gray and unnamed city is the Zone, a place guarded by barbed wire and soldiers, and where the normal laws of physics are victim to frequent anomalies. A stalker guides two men into the Zone, specifically to an area in which deep-seated desires are granted.'),
    ('tt15239678', '693134', 'Dune: Part Two', '2024',
    'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    'https://image.tmdb.org/t/p/w500/l6b9YZEokZl1nt7q0pprrur6btG.jpg',
    8.128, ARRAY[878, 12],
    'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a path of revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, Paul endeavors to prevent a terrible future only he can foresee.'),
    ('tt0087884', '655', 'Paris, Texas', '1984',
    'https://image.tmdb.org/t/p/w500/sP27Qm4THyRZyHjHYMfIDtJP6YE.jpg',
    'https://image.tmdb.org/t/p/w500/fWrq3u16gaBJ6nYNWcR3XaOhQPq.jpg',
    8.1, ARRAY[18],
    'A man wanders out of the desert not knowing who he is. His brother finds him, and helps to pull his memory back of the life he led before he walked out on his family and disappeared four years earlier.'),
    ('tt6710474', '545611', 'Everything Everywhere All at Once', '2022',
     'https://image.tmdb.org/t/p/w500/u68AjlvlutfEIcpmbYpKcdi09ut.jpg',
     'https://image.tmdb.org/t/p/w500/wp3vpSWAIjKSEeYb8F5NSZfONqw.jpg',
     7.718, ARRAY[28, 12, 878],
     'An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what''s important to her by connecting with the lives she could have led in other universes.'),
    ('tt3612616', '265177', 'Mommy', '2014',
     'https://image.tmdb.org/t/p/w500/uPDP0cHGOpkr47rdCdHWo4CyiPj.jpg',
     'https://image.tmdb.org/t/p/w500/pwoj3pRch3KKvq8t2plgpe5GDH5.jpg',
     8.2, ARRAY[18],
     'A peculiar neighbor offers hope to a recent widow who is struggling to raise a teenager who is unpredictable and, sometimes, violent.'),
    ('tt3783958', '313369', 'La La Land', '2016',
     'https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg',
     'https://image.tmdb.org/t/p/w500/2wmDyHz4gvF6m51IQZJnJzlLsnz.jpg',
     7.898, ARRAY[35, 18, 10749],
     'Mia, an aspiring actress, serves lattes to movie stars in between auditions and Sebastian, a jazz musician, scrapes by playing cocktail party gigs in dingy bars, but as success mounts they are faced with decisions that begin to fray the fragile fabric of their love affair, and the dreams they worked so hard to maintain in each other threaten to rip them apart.'),
    ('tt1527186', '62215', 'Melancholia', '2011',
     'https://image.tmdb.org/t/p/w500/fMneszMiQuTKY8JUXrGGB5vwqJf.jpg',
     'https://image.tmdb.org/t/p/w500/qzrS5ShZZPsPdhM5ZbcQKG7fwFo.jpg',
     7.155, ARRAY[18, 878],
     'Two sisters find their already strained relationship challenged as a mysterious new planet threatens to collide with Earth.'),
    ('tt17009710', '915935', 'Anatomy of a Fall', '2023',
     'https://image.tmdb.org/t/p/w500/1ho0d4LNZw3Y0voeKmSvPSgJOJ2.jpg',
     'https://image.tmdb.org/t/p/w500/kszooR7v1TLFM4pzx6IkKq2jDAN.jpg',
     7.517, ARRAY[53, 9648, 80],
     'A woman is suspected of her husband''s murder, and their blind son faces a moral dilemma as the sole witness.'),
    ('tt29002950', '878608', 'Resurrection', '2025',
     'https://image.tmdb.org/t/p/w500/n4YEPanrb976XfPKjSsHaIrlSt9.jpg',
     'https://image.tmdb.org/t/p/w500/sbmHT55N2aIwctQEY1pWOwRrxK0.jpg',
     7.292, ARRAY[878, 18],
     'In a future where humanity has surrendered its ability to dream in exchange for immortality, an outcast finds illusion, nightmarish visions, and beauty in an intoxicating world of his own making.'),
    ('tt5363618', '502033', 'Sound of Metal', '2020',
     'https://image.tmdb.org/t/p/w500/3178oOJKKPDeQ2legWQvMPpllv.jpg',
     'https://image.tmdb.org/t/p/w500/5TSWjyxOMVpCFrbJ9hDX0jF0S6v.jpg',
     7.701, ARRAY[18, 10402],
     'Metal drummer Ruben begins to lose his hearing. When a doctor tells him his condition will worsen, he thinks his career and life is over. His girlfriend Lou checks the former addict into a rehab for the deaf hoping it will prevent a relapse and help him adapt to his new life. After being welcomed and accepted just as he is, Ruben must choose between his new normal and the life he once knew.'),
    ('tt5083738', '375262', 'The Favourite', '2018',
     'https://image.tmdb.org/t/p/w500/cwBq0onfmeilU5xgqNNjJAMPfpw.jpg',
     'https://image.tmdb.org/t/p/w500/ekWMoBZ4B9rM60INZEh5FAD2HFR.jpg',
     7.5, ARRAY[36, 35, 18],
     'England, early 18th century. The close relationship between Queen Anne and Sarah Churchill is threatened by the arrival of Sarah''s cousin, Abigail Hill, resulting in a bitter rivalry between the two cousins to be the Queen''s favourite.'),
    ('tt1160419', '438631', 'Dune', '2021',
     'https://image.tmdb.org/t/p/w500/gDzOcq0pfeCeqMBwKIJlSmQpjkZ.jpg',
     'https://image.tmdb.org/t/p/w500/zRKQW58MBEY078AxkHxEJzUskCl.jpg',
     7.78, ARRAY[878, 12],
     'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planet''s exclusive supply of the most precious resource in existence-a commodity capable of unlocking humanity''s greatest potential-only those who can conquer their fear will survive.'),
    ('tt0347149', '4935', 'Howl''s Moving Castle', '2004',
    'https://image.tmdb.org/t/p/w500/13kOl2v0nD2OLbVSHnHk8GUFEhO.jpg',
    'https://image.tmdb.org/t/p/w500/bNYDRRgmKogbPjhsR0PTPkqITnh.jpg',
    8.388, ARRAY[14, 16, 12],
    'Sophie, a young milliner, is turned into an elderly woman by a witch who enters her shop and curses her. She encounters a wizard named Howl and gets caught up in his resistance to fighting for the king.'),
    ('tt27613895', '1297842', 'GOAT', '2026',
     'https://image.tmdb.org/t/p/w500/wfuqMlaExcoYiUEvKfVpUTt1v4u.jpg',
     'https://image.tmdb.org/t/p/w500/imkZLxabgZBdsWPnkPkFCHC9NCw.jpg',
     8.145, ARRAY[16, 35, 10751],
     'A small goat with big dreams gets a once-in-a-lifetime shot to join the pros and play roarball, a high-intensity, co-ed, full-contact sport dominated by the fastest, fiercest animals in the world.'),
    ('tt12299608', '696506', 'Mickey 17', '2025',
    'https://image.tmdb.org/t/p/w500/edKpE9B5qN3e559OuMCLZdW1iBZ.jpg',
    'https://image.tmdb.org/t/p/w500/9PRKAdrDvAdCfg3EcApLTfzGsEt.jpg',
    6.837, ARRAY[878, 35, 12],
    'Unlikely hero Mickey Barnes finds himself in the extraordinary circumstance of working for an employer who demands the ultimate commitment to the job… to die, for a living.')
ON CONFLICT (imdbid) DO NOTHING;

INSERT INTO featured_movies (imdbid) VALUES
    ('tt14905854'),
    ('tt6751668'),
    ('tt5726616'),
    ('tt26443616'),
    ('tt33071426'),
    ('tt0078788'),
    ('tt17009710'),
    ('tt3612616'),
    ('tt29623480'),
    ('tt10457128'),
    ('tt1650048'),
    ('tt1527186'),
    ('tt1160419'),
    ('tt12042730'),
    ('tt15239678'),
    ('tt1757678'),
    ('tt0087884'),
    ('tt0816692'),
    ('tt5083738'),
    ('tt3783958'),
    ('tt8613070'),
    ('tt5363618'),
    ('tt0079944'),
    ('tt6710474'),
    ('tt0347149'),
    ('tt29002950'),
    ('tt0468569'),
    ('tt4633694'),
    ('tt28650488'),
    ('tt10370710'),
    ('tt32916440'),
    ('tt27613895'),
    ('tt12299608')
ON CONFLICT (imdbid) DO NOTHING;
