# Generated by Django 6.1 on 2026-08-07 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, unique=True)),
                ('tmdb_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=10)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('backdrop_url', models.URLField(blank=True, null=True)),
                ('note', models.FloatField(default=0)),
                ('runtime_minutes', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('director', models.CharField(blank=True, max_length=255)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.genre')),
            ],
        ),
    ]
